url = https://demo.guru99.com/V1/index.php
username = mngr615012
password = UhurUva
browserName = chrome
isHeadLess = true1
EdgeBrowserName = edge
configFileLocation = C:\\Users\\codin\\Automation Projects\\Project1\\src\\main\\java\\com\\Config\\Config.properties
driverLocation = C:\\Users\\codin\\Drivers\\chromedriver-win64\\chromedriver.exe
edgeDriverLocation = C:\\Users\\codin\\Drivers\\edgedriver_win64\\msedgedriver.exe
chromeBrowser = webdriver.chrome.driver
edgeDriver = webdriver.edge.driver
excel_location = C:\\Users\\codin\\Automation Projects\\Project1\\src\\main\\java\\com\\testData\\testdata.xlsx
